name: school_management_system
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.16.1 <3.0.0'
dependencies:
  cloud_firestore: ^3.3.0
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  dio: ^4.0.6
  file_picker: ^4.6.1
  firebase_auth: ^3.4.2
  firebase_messaging: ^12.0.0
  firebase_storage: ^10.3.2
  flutter:
    sdk: flutter
  flutter_downloader: ^1.7.0
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.10.0
  flutter_local_notifications: ^9.7.0
  flutter_phoenix: ^1.0.0
  flutter_screenutil: 5.0.0
  flutter_svg: ^1.0.0
  flutter_zoom_drawer: ^3.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.3
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  open_file: ^3.2.1
  path_provider: ^2.0.11
  permission_handler: ^9.2.0
  rounded_loading_button: ^2.0.9
  shimmer: ^2.0.0
  table_calendar: ^3.0.6
  url_launcher: ^6.1.4
  youtube_player_flutter: ^8.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/LOGO2.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: RedHatDisplay-Bold
      fonts:
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
    - family: RedHatDisplay-Light
      fonts:
        - asset: assets/fonts/RedHatDisplay-Light.ttf
    - family: RedHatDisplay-Medium
      fonts:
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
    - family: RedHatDisplay-Regular
      fonts:
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
    - family: SFProDisplay-Bold
      fonts:
        - asset: assets/fonts/SFProDisplay-Bold.OTF
    - family: SFProDisplay-Medium
      fonts:
        - asset: assets/fonts/SFProDisplay-Medium.OTF
    - family: SFProDisplay-Regular
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.OTF

# To add assets to your application, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
